const GETTING_DOCTOR_APPOINTMENTS = 'GETTING_DOCTOR_APPOINTMENTS';
const GOT_DOCTOR_APPOINTMENTS = 'GOT_DOCTOR_APPOINTMENTS';
const GOT_DOCTOR_APPOINTMENTS_ERROR = 'GOT_DOCTOR_APPOINTMENTS_ERROR';

const GETTING_PATIENT_MEDICAL_RECORD = 'GETTING_DOCTOR_APPOINTMENTS';
const GOT_PATIENT_MEDICAL_RECORD = 'GOT_PATIENT_MEDICAL_RECORD';
const GOT_PATIENT_MEDICAL_RECORD_ERROR = 'GOT_DOCTOR_APPOINTMENTS_ERROR';

const POSTING_PATIENT_MEDICAL_RECORD = 'POSTING_PATIENT_MEDICAL_RECORD';
const POSTED_PATIENT_MEDICAL_RECORD = 'POSTED_PATIENT_MEDICAL_RECORD';
const POSTED_PATIENT_MEDICAL_RECORD_ERROR = 'POSTED_PATIENT_MEDICAL_RECORD_ERROR';

const GETTING_DOCTOR_INFO = 'GETTING_DOCTOR_INFO';
const GOT_DOCTOR_INFO = 'GOT_DOCTOR_INFO';
const GOT_DOCTOR_INFO_ERROR = 'GOT_DOCTOR_INFO_ERROR';

const FETCH_POSTS = 'FETCH_POSTS';

const constants = {
    GETTING_DOCTOR_APPOINTMENTS,
    GOT_DOCTOR_APPOINTMENTS,
    GOT_DOCTOR_APPOINTMENTS_ERROR,

    GETTING_PATIENT_MEDICAL_RECORD,
    GOT_PATIENT_MEDICAL_RECORD,
    GOT_PATIENT_MEDICAL_RECORD_ERROR,

    GETTING_DOCTOR_INFO,
    GOT_DOCTOR_INFO,
    GOT_DOCTOR_INFO_ERROR,

    FETCH_POSTS
};

export default constants;