const GETTING_DOCTOR_APPOINTMENTS = 'GETTING_DOCTOR_APPOINTMENTS';
const GOT_DOCTOR_APPOINTMENTS = 'GOT_DOCTOR_APPOINTMENTS';
const GOT_DOCTOR_APPOINTMENTS_ERROR = 'GOT_DOCTOR_APPOINTMENTS_ERROR';

const GETTING_DOCTOR_INFO = 'GETTING_DOCTOR_INFO';
const GOT_DOCTOR_INFO = 'GOT_DOCTOR_INFO';
const GOT_DOCTOR_INFO_ERROR = 'GOT_DOCTOR_INFO_ERROR';

const FETCH_POSTS = 'FETCH_POSTS';

const constants = {
    GETTING_DOCTOR_APPOINTMENTS,
    GOT_DOCTOR_APPOINTMENTS,
    GOT_DOCTOR_APPOINTMENTS_ERROR,

    GETTING_DOCTOR_INFO,
    GOT_DOCTOR_INFO,
    GOT_DOCTOR_INFO_ERROR,

    FETCH_POSTS
};

export default constants;